Set-StrictMode -Version Latest

function Get-DefaultEnvTemplate {
    <#
    .SYNOPSIS
        Returns the default .env file template content.
    #>
    @"
# LLM Workflow Environment Configuration
# Generated by llmheal on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# =============================================================================
# ContextLattice Configuration
# =============================================================================
CONTEXTLATTICE_ORCHESTRATOR_URL=http://127.0.0.1:8075
CONTEXTLATTICE_ORCHESTRATOR_API_KEY=your-api-key-here

# =============================================================================
# LLM Provider API Keys (at least one required)
# =============================================================================
# OpenAI
# OPENAI_API_KEY=sk-your-key-here

# Anthropic Claude
# ANTHROPIC_API_KEY=sk-ant-your-key-here

# Kimi (Moonshot)
# KIMI_API_KEY=your-kimi-key-here

# Google Gemini
# GEMINI_API_KEY=your-gemini-key-here

# GLM (Zhipu)
# GLM_API_KEY=your-glm-key-here
# GLM_BASE_URL=https://open.bigmodel.cn/api/paas/v4

# Ollama (local)
# OLLAMA_BASE_URL=http://localhost:11434/v1

# =============================================================================
# Optional Configuration
# =============================================================================
# CONTEXTLATTICE_PROJECT_NAME=my-project
# MEMPALACE_PALACE_PATH=~/.mempalace/palace
"@
}

function Get-DefaultBridgeConfig {
    <#
    .SYNOPSIS
        Returns the default bridge.config.json content.
    #>
    @"
{
  "`$schema": "./bridge.config.schema.json",
  "version": "2.0",
  "orchestratorUrl": "http://127.0.0.1:8075",
  "apiKeyEnvVar": "CONTEXTLATTICE_ORCHESTRATOR_API_KEY",
  "defaultProjectName": "my-project",
  "palaces": [
    {
      "path": "~/.mempalace/palace",
      "collectionName": "mempalace_drawers",
      "topicPrefix": "mempalace",
      "wingProjectMap": {
        "default_wing": "my-project"
      }
    }
  ],
  "syncOptions": {
    "batchSize": 250,
    "workers": 4,
    "strict": false
  }
}
"@
}


