#requires -Version 5.1
Set-StrictMode -Version Latest
<#
.SYNOPSIS
    Inter-pack transport with PS 5.1-safe JSON, artifact-backed export/import, provenance, and rollback.
#>
$script:InterPackSchemaVersion = 1
$script:DefaultPipelinesDirectory = '.llm-workflow/interpack/pipelines'
$script:DefaultTransformsDirectory = '.llm-workflow/interpack/transforms'
$script:DefaultIntermediateDirectory = '.llm-workflow/interpack/intermediate'
$script:DefaultProvenanceDirectory = '.llm-workflow/interpack/provenance'
$script:AssetTypes = @{ mesh=@{extensions=@('.glb','.gltf','.obj','.fbx')}; material=@{extensions=@('.material','.tres','.json')}; animation=@{extensions=@('.anim','.gltf','.json')}; texture=@{extensions=@('.png','.jpg','.webp','.tga')}; sprite=@{extensions=@('.png','.jpg','.webp')}; scene=@{extensions=@('.tscn','.escn','.json')} }
function ConvertTo-InterPackHashtable { [CmdletBinding()] param([Parameter(Mandatory)]$InputObject) if ($null -eq $InputObject) { return $null }; if ($InputObject -is [hashtable]) { return $InputObject }; if ($InputObject -is [System.Collections.IDictionary]) { $h=@{}; foreach($k in $InputObject.Keys){$h[$k]=ConvertTo-InterPackHashtable $InputObject[$k]}; return $h }; if ($InputObject -is [System.Collections.IEnumerable] -and -not ($InputObject -is [string])) { return @($InputObject | ForEach-Object { ConvertTo-InterPackHashtable $_ }) }; if ($InputObject.PSObject.Properties.Count -gt 0 -and $InputObject.GetType().Name -eq 'PSCustomObject') { $h=@{}; foreach($p in $InputObject.PSObject.Properties){$h[$p.Name]=ConvertTo-InterPackHashtable $p.Value}; return $h }; $InputObject }
function Read-InterPackJson { [CmdletBinding()] param([Parameter(Mandatory)][string]$Path) ConvertTo-InterPackHashtable (Get-Content -LiteralPath $Path -Raw -ErrorAction Stop | ConvertFrom-Json) }
function Write-InterPackJson { [CmdletBinding()] param([Parameter(Mandatory)]$Data,[Parameter(Mandatory)][string]$Path) $parent=Split-Path -Parent $Path; if($parent -and -not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null}; $Data|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $Path -Encoding UTF8 }
function Resolve-InterPackRoot { [CmdletBinding()] param([string]$ProjectRoot='.') try{(Resolve-Path -LiteralPath $ProjectRoot -ErrorAction Stop).Path}catch{throw "Project root not found: $ProjectRoot"} }
function New-InterPackRunId { (Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ') + '-' + ([guid]::NewGuid().ToString('N').Substring(0,8)) }
function New-InterPackPipeline {
    [CmdletBinding()] [OutputType([hashtable])]
    param([Parameter(Mandatory)][ValidateSet('blender-engine','godot-engine','rpgmaker-mz')][string]$SourcePack,[Parameter(Mandatory)][ValidateSet('blender-engine','godot-engine','rpgmaker-mz')][string]$TargetPack,[ValidateSet('mesh','material','animation','texture','sprite','scene')][string[]]$AssetTypes=@('mesh','material','animation'),[hashtable]$TransformRules=@{},[string[]]$ValidationCheckpoints=@('pre-export','post-export','pre-import','post-import'),[string]$IntermediateFormat='json',[string]$ProjectRoot='.',[hashtable]$Metadata=@{})
    if($SourcePack -eq $TargetPack){throw "Source pack and target pack cannot be the same: $SourcePack"}; $root=Resolve-InterPackRoot $ProjectRoot; $id='pipeline-{0}-{1}-{2}' -f $SourcePack,$TargetPack,(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ')
    if($TransformRules.Count -eq 0){foreach($type in $AssetTypes){$TransformRules[$type]=@{sourceFormat="$($SourcePack.Split('-')[0])_$type";targetFormat="$($TargetPack.Split('-')[0])_$type";versionRange='>=1.0.0'}}}
    $pipeline=[ordered]@{schemaVersion=$script:InterPackSchemaVersion;pipelineId=$id;sourcePack=$SourcePack;targetPack=$TargetPack;assetTypes=$AssetTypes;transformRules=$TransformRules;validationCheckpoints=$ValidationCheckpoints;intermediateFormat=$IntermediateFormat;projectRoot=$root;createdUtc=(Get-Date).ToUniversalTime().ToString('o');status='created';metadata=$Metadata;provenanceEnabled=$true;incrementalSyncEnabled=$true}
    Write-InterPackJson $pipeline (Join-Path (Join-Path $root $script:DefaultPipelinesDirectory) "$id.json"); $pipeline
}
function Get-InterPackPipeline {
    [CmdletBinding()] param([string]$PipelineId,[string]$SourcePack,[string]$TargetPack,[string]$ProjectRoot='.')
    $dir=Join-Path (Resolve-InterPackRoot $ProjectRoot) $script:DefaultPipelinesDirectory; if(-not(Test-Path -LiteralPath $dir)){return $null}
    if($PipelineId){$path=Join-Path $dir "$PipelineId.json"; if(Test-Path -LiteralPath $path){return Read-InterPackJson $path}; return $null}
    $items=@(); foreach($file in Get-ChildItem -Path $dir -Filter '*.json' -File){$p=Read-InterPackJson $file.FullName; if($SourcePack -and $p.sourcePack -ne $SourcePack){continue}; if($TargetPack -and $p.targetPack -ne $TargetPack){continue}; $items+=$p}; $items
}
function Register-InterPackTransform {
    [CmdletBinding()] [OutputType([hashtable])]
    param([Parameter(Mandatory)][string]$SourceFormat,[Parameter(Mandatory)][string]$TargetFormat,[Parameter(Mandatory)][object]$TransformFunction,[string]$Version='1.0.0',[string]$Description='',[hashtable]$Parameters=@{},[string]$ProjectRoot='.')
    $id="$SourceFormat-to-$TargetFormat"; $root=Resolve-InterPackRoot $ProjectRoot; $transform=[ordered]@{schemaVersion=$script:InterPackSchemaVersion;transformId=$id;sourceFormat=$SourceFormat;targetFormat=$TargetFormat;transformFunction=if($TransformFunction -is [scriptblock]){$TransformFunction.ToString()}else{[string]$TransformFunction};version=$Version;description=$Description;parameters=$Parameters;registeredUtc=(Get-Date).ToUniversalTime().ToString('o')}
    Write-InterPackJson $transform (Join-Path (Join-Path $root $script:DefaultTransformsDirectory) "$id.json"); $transform
}
function Get-InterPackTransform { [CmdletBinding()] [OutputType([hashtable])] param([Parameter(Mandatory)][string]$SourceFormat,[Parameter(Mandatory)][string]$TargetFormat,[string]$ProjectRoot='.') $path=Join-Path (Join-Path (Resolve-InterPackRoot $ProjectRoot) $script:DefaultTransformsDirectory) "$SourceFormat-to-$TargetFormat.json"; if(Test-Path -LiteralPath $path){Read-InterPackJson $path}else{$null} }
function Invoke-InterPackTransform { [CmdletBinding()] param([Parameter(Mandatory)][hashtable]$Transform,[Parameter(Mandatory)]$InputData,[hashtable]$Parameters=@{}) try{$all=@{}; if($Transform.parameters){foreach($k in $Transform.parameters.Keys){$all[$k]=$Transform.parameters[$k]}}; foreach($k in $Parameters.Keys){$all[$k]=$Parameters[$k]}; $all.Input=$InputData; @{success=$true;data=(& ([scriptblock]::Create($Transform.transformFunction)) @all);errors=@()}}catch{@{success=$false;data=$null;errors=@($_.Exception.Message)}} }
function Get-InterPackPipelineStatus {
    [CmdletBinding()] [OutputType([hashtable])] param([string]$PipelineId,[string]$ProjectRoot='.')
    $pipelines=if($PipelineId){@(Get-InterPackPipeline -PipelineId $PipelineId -ProjectRoot $ProjectRoot)}else{@(Get-InterPackPipeline -ProjectRoot $ProjectRoot)}; $result=@{schemaVersion=$script:InterPackSchemaVersion;checkedAt=(Get-Date).ToUniversalTime().ToString('o');overallStatus='healthy';pipelines=@();warnings=@();errors=@()}
    if(-not $pipelines){$result.overallStatus='no-pipelines'; return $result}; foreach($p in $pipelines){$health=@(); foreach($type in $p.assetTypes){$rule=$p.transformRules[$type]; $t=if($rule){Get-InterPackTransform -SourceFormat $rule.sourceFormat -TargetFormat $rule.targetFormat -ProjectRoot $ProjectRoot}else{$null}; $health+=@{assetType=$type;available=($null-ne$t);version=if($t){$t.version}else{$null}}}; $missing=@($health|Where-Object{-not $_.available}); if($missing.Count -gt 0){$result.overallStatus='degraded'}; $result.pipelines+=@{pipelineId=$p.pipelineId;sourcePack=$p.sourcePack;targetPack=$p.targetPack;status=if($missing.Count){'missing-transforms'}else{'healthy'};transformHealth=$health}}
    $result
}
function Invoke-InterPackExport {
    [CmdletBinding()] [OutputType([hashtable])]
    param([Parameter(Mandatory)][hashtable]$Pipeline,[string[]]$AssetIds=@(),[ValidateSet('mesh','material','animation','texture','sprite','scene')][string]$AssetType='',[string]$Query='',[string]$OutputDirectory='',[switch]$Validate,[string]$RunId='')
    if(-not $RunId){$RunId=New-InterPackRunId}; if($Query){throw 'Query-based inter-pack export is not implemented. Provide explicit AssetIds so the export is deterministic.'}; if($AssetIds.Count -eq 0){throw 'At least one AssetId is required for inter-pack export.'}; if([string]::IsNullOrWhiteSpace($AssetType)){throw 'AssetType is required when exporting explicit AssetIds.'}
    $dir=if($OutputDirectory){$OutputDirectory}else{Join-Path $Pipeline.projectRoot "$script:DefaultIntermediateDirectory/$RunId"}; if(-not(Test-Path -LiteralPath $dir)){New-Item -ItemType Directory -Path $dir -Force|Out-Null}
    $result=@{runId=$RunId;pipelineId=$Pipeline.pipelineId;sourcePack=$Pipeline.sourcePack;operation='export';success=$true;exportedAssets=@();failedAssets=@();outputDirectory=$dir;startedAt=(Get-Date).ToUniversalTime().ToString('o');completedAt=$null}
    foreach($id in $AssetIds){try{$rule=$Pipeline.transformRules[$AssetType]; if(-not $rule){throw "No transform rule defined for asset type: $AssetType"}; $file=Join-Path $dir "$id.$($Pipeline.intermediateFormat).json"; $data=[ordered]@{schemaVersion=$script:InterPackSchemaVersion;pipelineId=$Pipeline.pipelineId;runId=$RunId;sourcePack=$Pipeline.sourcePack;assetId=$id;assetType=$AssetType;sourceFormat=$rule.sourceFormat;exportedAt=(Get-Date).ToUniversalTime().ToString('o');data=@{assetId=$id;assetType=$AssetType;format=$Pipeline.intermediateFormat;sourcePack=$Pipeline.sourcePack}}; Write-InterPackJson $data $file; if($Validate){$v=Test-InterPackIntermediate -IntermediatePath $file -AssetType $AssetType; if(-not $v.valid){throw "Validation failed: $($v.errors -join ', ')"}}; $result.exportedAssets+=@{assetId=$id;assetType=$AssetType;success=$true;outputPath=$file}}catch{$result.failedAssets+=@{assetId=$id;assetType=$AssetType;success=$false;errors=@($_.Exception.Message)}; $result.success=$false}}
    $result.completedAt=(Get-Date).ToUniversalTime().ToString('o'); $result
}
function Invoke-InterPackImport {
    [CmdletBinding()] [OutputType([hashtable])]
    param([Parameter(Mandatory)][hashtable]$Pipeline,[Parameter(Mandatory)][string[]]$IntermediatePaths,[string]$TargetDirectory='',[switch]$Validate,[switch]$PreserveMetadata=$true,[string]$RunId='')
    if(-not $RunId){$RunId=New-InterPackRunId}; $targetDir=if($TargetDirectory){$TargetDirectory}else{Join-Path $Pipeline.projectRoot "packs/imports/$($Pipeline.targetPack)/$RunId"}; if(-not(Test-Path -LiteralPath $targetDir)){New-Item -ItemType Directory -Path $targetDir -Force|Out-Null}
    $result=@{runId=$RunId;pipelineId=$Pipeline.pipelineId;targetPack=$Pipeline.targetPack;operation='import';success=$true;importedAssets=@();failedAssets=@();targetDirectory=$targetDir;startedAt=(Get-Date).ToUniversalTime().ToString('o');completedAt=$null}
    foreach($path in $IntermediatePaths){try{if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Intermediate file not found: $path"}; $intermediate=Read-InterPackJson $path; if($Validate){$v=Test-InterPackIntermediate -IntermediateData $intermediate; if(-not $v.valid){throw "Pre-import validation failed: $($v.errors -join ', ')"}}; $assetId=$intermediate.assetId; $assetType=$intermediate.assetType; $rule=$Pipeline.transformRules[$assetType]; if(-not $rule){throw "No transform rule for asset type: $assetType"}; $ext=switch($Pipeline.targetPack){'godot-engine'{'.tres'}'blender-engine'{'.json'}'rpgmaker-mz'{'.json'}default{'.json'}}; $target=Join-Path $targetDir "$assetId$ext"; $targetData=[ordered]@{schemaVersion=$script:InterPackSchemaVersion;pipelineId=$Pipeline.pipelineId;runId=$RunId;sourcePack=$Pipeline.sourcePack;targetPack=$Pipeline.targetPack;assetId=$assetId;assetType=$assetType;importedAt=(Get-Date).ToUniversalTime().ToString('o');sourceData=if($PreserveMetadata){$intermediate}else{$null};data=@{converted=$true;targetFormat=$rule.targetFormat;sourceIntermediate=$path}}; Write-InterPackJson $targetData $target; if($Pipeline.provenanceEnabled){Save-InterPackProvenance -Pipeline $Pipeline -RunId $RunId -AssetId $assetId -AssetType $assetType -SourcePath $path -TargetPath $target -SourceFormat $intermediate.sourceFormat -TargetFormat $rule.targetFormat|Out-Null}; $result.importedAssets+=@{intermediatePath=$path;success=$true;targetPath=$target}}catch{$result.failedAssets+=@{intermediatePath=$path;success=$false;errors=@($_.Exception.Message)}; $result.success=$false}}
    $result.completedAt=(Get-Date).ToUniversalTime().ToString('o'); $result
}
function Save-InterPackProvenance { [CmdletBinding()] param([Parameter(Mandatory)][hashtable]$Pipeline,[Parameter(Mandatory)][string]$RunId,[Parameter(Mandatory)][string]$AssetId,[string]$AssetType,[string]$SourcePath,[string]$TargetPath,[string]$SourceFormat,[string]$TargetFormat) $prov=[ordered]@{schemaVersion=$script:InterPackSchemaVersion;runId=$RunId;pipelineId=$Pipeline.pipelineId;sourcePack=$Pipeline.sourcePack;targetPack=$Pipeline.targetPack;assetId=$AssetId;assetType=$AssetType;sourceFormat=$SourceFormat;targetFormat=$TargetFormat;sourcePath=$SourcePath;targetPath=$TargetPath;recordedAt=(Get-Date).ToUniversalTime().ToString('o')}; $path=Join-Path (Join-Path $Pipeline.projectRoot $script:DefaultProvenanceDirectory) "$RunId-$AssetId.json"; Write-InterPackJson $prov $path; $prov }
function Test-InterPackIntermediate { [CmdletBinding()] [OutputType([hashtable])] param([string]$IntermediatePath,[hashtable]$IntermediateData,[string]$AssetType='') if($IntermediatePath){$IntermediateData=Read-InterPackJson $IntermediatePath}; $errors=@(); foreach($field in @('schemaVersion','pipelineId','runId','sourcePack','assetId','assetType','sourceFormat','data')){if(-not $IntermediateData.ContainsKey($field)){$errors+="Missing field: $field"}}; if($AssetType -and $IntermediateData.assetType -ne $AssetType){$errors+="Asset type mismatch: expected $AssetType got $($IntermediateData.assetType)"}; @{valid=($errors.Count -eq 0);errors=$errors} }
function Test-InterPackCompatibility { [CmdletBinding()] [OutputType([hashtable])] param([string]$SourcePack,[string]$TargetPack) $ok=($SourcePack -ne $TargetPack); @{isCompatible=$ok;sourcePack=$SourcePack;targetPack=$TargetPack;errors=if($ok){@()}else{@('Source and target packs cannot match')}} }
function Sync-InterPackAssets { [CmdletBinding()] [OutputType([hashtable])] param([Parameter(Mandatory)][hashtable]$Pipeline,[Parameter(Mandatory)][string[]]$AssetIds,[Parameter(Mandatory)][ValidateSet('mesh','material','animation','texture','sprite','scene')][string]$AssetType,[switch]$Validate,[string]$RunId='') if(-not$RunId){$RunId=New-InterPackRunId}; $export=Invoke-InterPackExport -Pipeline $Pipeline -AssetIds $AssetIds -AssetType $AssetType -Validate:$Validate -RunId $RunId; $paths=@($export.exportedAssets|ForEach-Object{$_.outputPath}); $import=Invoke-InterPackImport -Pipeline $Pipeline -IntermediatePaths $paths -Validate:$Validate -RunId $RunId; @{runId=$RunId;pipelineId=$Pipeline.pipelineId;success=($export.success -and $import.success);export=$export;import=$import} }
function Rollback-InterPackSync { [CmdletBinding()] [OutputType([hashtable])] param([Parameter(Mandatory)][string]$RunId,[string]$ProjectRoot='.') $root=Resolve-InterPackRoot $ProjectRoot; $removed=@(); foreach($dir in @($script:DefaultIntermediateDirectory,$script:DefaultProvenanceDirectory,'packs/imports')){ $path=Join-Path $root $dir; if(Test-Path -LiteralPath $path){Get-ChildItem -Path $path -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.Name -like "*$RunId*" -or $_.FullName -like "*$RunId*" } | ForEach-Object { $removed+=$_.FullName; Remove-Item -LiteralPath $_.FullName -Force }}}; @{runId=$RunId;success=$true;removed=$removed} }
