#requires -Version 5.1
<#
.SYNOPSIS
    Git Hooks integration for LLM Workflow platform.

.DESCRIPTION
    Provides Git hook installation, management, and execution functions for the
    LLM Workflow platform. Supports pre-commit, post-commit, pre-push, and post-merge
    hooks with secret scanning, health checks, and policy enforcement.

.NOTES
    File Name      : GitHooks.ps1
    Author         : LLM Workflow Team
    Version        : 0.4.0
    Compatible with: PowerShell 5.1+
    Canonical Ref  : Part 1 Section 20
#>

Set-StrictMode -Version Latest

#===============================================================================
# Configuration and Constants
#===============================================================================

$script:ValidHookTypes = @('pre-commit', 'post-commit', 'pre-push', 'post-merge')
$script:HookScriptHeader = @'
#!/usr/bin/env pwsh
# LLM Workflow Git Hook
# Auto-generated by LLMWorkflow - DO NOT EDIT
# Generated: {0}

$ErrorActionPreference = 'Stop'

# Ensure module is available
try {
    Import-Module LLMWorkflow -ErrorAction Stop
} catch {
    Write-Error "Failed to import LLMWorkflow module: $_"
    exit 1
}

# Run hook logic
'@

$script:HookScriptFooter = @'
exit $result.ExitCode
'@

#===============================================================================
# Hook Installation Functions
#===============================================================================

function Install-LLMWorkflowGitHooks {
    <#
    .SYNOPSIS
        Installs LLM Workflow Git hooks into .git/hooks.

    .DESCRIPTION
        Installs the specified Git hooks for the LLM Workflow platform.
        Supports pre-commit (secret scanning, health check), post-commit (auto-sync),
        pre-push (validation, compatibility check), and post-merge (rebuild packs).
        Optionally backs up existing hooks before overwriting.

    .PARAMETER ProjectRoot
        Path to the project root containing the .git directory. Defaults to current directory.

    .PARAMETER Hooks
        Array of hook types to install: pre-commit, post-commit, pre-push, post-merge.
        Defaults to all hooks.

    .PARAMETER BackupExisting
        If specified, existing hooks will be backed up before being overwritten.

    .PARAMETER Global
        If specified, installs hooks to the global Git hooksPath instead of local .git/hooks.

    .EXAMPLE
        Install-LLMWorkflowGitHooks
        Installs all hooks to the current project's .git/hooks directory.

    .EXAMPLE
        Install-LLMWorkflowGitHooks -Hooks @('pre-commit', 'pre-push') -BackupExisting
        Installs only pre-commit and pre-push hooks, backing up any existing ones.

    .OUTPUTS
        PSCustomObject with installation results.
    #>
    [CmdletBinding(SupportsShouldProcess = $true)]
    param(
        [Parameter()]
        [string]$ProjectRoot = '.',

        [Parameter()]
        [ValidateSet('pre-commit', 'post-commit', 'pre-push', 'post-merge')]
        [string[]]$Hooks = $script:ValidHookTypes,

        [Parameter()]
        [switch]$BackupExisting,

        [Parameter()]
        [switch]$Global
    )

    # Resolve project root
    $resolvedRoot = Resolve-Path -LiteralPath $ProjectRoot -ErrorAction SilentlyContinue
    if (-not $resolvedRoot) {
        throw "Project root does not exist: $ProjectRoot"
    }
    $resolvedRoot = $resolvedRoot.Path

    # Determine hooks directory
    $hooksDir = if ($Global) {
        $globalHooksPath = & git config --global core.hooksPath 2>$null
        if ($globalHooksPath) {
            $globalHooksPath
        } else {
            $defaultGlobalDir = if ($IsWindows -or ($PSVersionTable.PSVersion.Major -lt 6)) {
                Join-Path $HOME '.git-hooks'
            } else {
                Join-Path $HOME '.config/git/hooks'
            }
            # Ensure global hooks directory exists and configure Git
            if (-not (Test-Path -LiteralPath $defaultGlobalDir)) {
                New-Item -ItemType Directory -Path $defaultGlobalDir -Force | Out-Null
            }
            & git config --global core.hooksPath $defaultGlobalDir
            $defaultGlobalDir
        }
    } else {
        $gitDir = Join-Path $resolvedRoot '.git'
        if (-not (Test-Path -LiteralPath $gitDir)) {
            throw "No .git directory found in $resolvedRoot. Initialize a Git repository first."
        }
        Join-Path $gitDir 'hooks'
    }

    # Ensure hooks directory exists
    if (-not (Test-Path -LiteralPath $hooksDir)) {
        New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
    }

    $results = @{
        Installed = @()
        BackedUp = @()
        Skipped = @()
        Failed = @()
    }

    foreach ($hookType in $Hooks) {
        $hookPath = Join-Path $hooksDir $hookType
        $backupPath = "$hookPath.backup.$(Get-Date -Format 'yyyyMMdd_HHmmss')"

        # Check for existing hook
        if (Test-Path -LiteralPath $hookPath) {
            if ($BackupExisting) {
                if ($PSCmdlet.ShouldProcess("Backup $hookType hook", "Backup")) {
                    try {
                        Copy-Item -LiteralPath $hookPath -Destination $backupPath -Force
                        $results.BackedUp += @{
                            HookType = $hookType
                            BackupPath = $backupPath
                        }
                    } catch {
                        $results.Failed += @{
                            HookType = $hookType
                            Reason = "Failed to backup existing hook: $_"
                        }
                        continue
                    }
                }
            }
        }

        if ($PSCmdlet.ShouldProcess("Install $hookType hook to $hookPath", "Install")) {
            try {
                # Generate hook script content
                $hookContent = New-GitHookScript -HookType $hookType -ProjectRoot $resolvedRoot

                # Write hook script
                $hookContent | Out-File -LiteralPath $hookPath -Encoding UTF8 -Force

                # Set executable permissions on Unix-like systems
                if (-not ($IsWindows -or ($PSVersionTable.PSVersion.Major -lt 6))) {
                    chmod +x $hookPath
                }

                $results.Installed += $hookType

                # Log installation
                Write-GitHookLog -HookType $hookType -Action 'Install' -Status 'Success' -ProjectRoot $resolvedRoot
            } catch {
                $results.Failed += @{
                    HookType = $hookType
                    Reason = $_.Exception.Message
                }
            }
        } else {
            $results.Skipped += $hookType
        }
    }

    # Write summary
    $summary = [PSCustomObject]@{
        ProjectRoot = $resolvedRoot
        HooksDirectory = $hooksDir
        IsGlobal = $Global.IsPresent
        InstalledCount = $results.Installed.Count
        BackedUpCount = $results.BackedUp.Count
        FailedCount = $results.Failed.Count
        Installed = $results.Installed
        BackedUp = $results.BackedUp
        Failed = $results.Failed
    }

    return $summary
}

function Uninstall-LLMWorkflowGitHooks {
    <#
    .SYNOPSIS
        Removes installed LLM Workflow Git hooks.

    .DESCRIPTION
        Uninstalls the specified Git hooks from the .git/hooks directory.
        Optionally restores from backup if available.

    .PARAMETER ProjectRoot
        Path to the project root containing the .git directory. Defaults to current directory.

    .PARAMETER Hooks
        Array of hook types to uninstall. Defaults to all hooks.

    .PARAMETER RestoreBackup
        If specified and a backup exists, restores the backup instead of removing.

    .PARAMETER KeepBackup
        If specified alongside RestoreBackup, keeps the backup file after restoration.

    .EXAMPLE
        Uninstall-LLMWorkflowGitHooks
        Removes all LLM Workflow hooks from the current project.

    .EXAMPLE
        Uninstall-LLMWorkflowGitHooks -Hooks @('pre-commit') -RestoreBackup
        Restores the pre-commit hook from its most recent backup.

    .OUTPUTS
        PSCustomObject with uninstallation results.
    #>
    [CmdletBinding(SupportsShouldProcess = $true)]
    param(
        [Parameter()]
        [string]$ProjectRoot = '.',

        [Parameter()]
        [ValidateSet('pre-commit', 'post-commit', 'pre-push', 'post-merge')]
        [string[]]$Hooks = $script:ValidHookTypes,

        [Parameter()]
        [switch]$RestoreBackup,

        [Parameter()]
        [switch]$KeepBackup
    )

    # Resolve project root
    $resolvedRoot = Resolve-Path -LiteralPath $ProjectRoot -ErrorAction SilentlyContinue
    if (-not $resolvedRoot) {
        throw "Project root does not exist: $ProjectRoot"
    }
    $resolvedRoot = $resolvedRoot.Path

    $hooksDir = Join-Path $resolvedRoot '.git' 'hooks'
    if (-not (Test-Path -LiteralPath $hooksDir)) {
        throw "No .git/hooks directory found in $resolvedRoot"
    }

    $results = @{
        Removed = @()
        Restored = @()
        NotFound = @()
        Failed = @()
    }

    foreach ($hookType in $Hooks) {
        $hookPath = Join-Path $hooksDir $hookType

        if (-not (Test-Path -LiteralPath $hookPath)) {
            $results.NotFound += $hookType
            continue
        }

        # Check if it's an LLM Workflow hook
        $content = Get-Content -LiteralPath $hookPath -Raw -ErrorAction SilentlyContinue
        $isLLMWorkflowHook = $content -and ($content -match 'LLM Workflow Git Hook')

        if (-not $isLLMWorkflowHook) {
            Write-Warning "Hook $hookType does not appear to be an LLM Workflow hook. Skipping."
            $results.NotFound += $hookType
            continue
        }

        if ($RestoreBackup) {
            # Find most recent backup
            $backupPattern = "$hookPath.backup.*"
            $backups = Get-ChildItem -Path $backupPattern -ErrorAction SilentlyContinue | 
                Sort-Object LastWriteTime -Descending

            if ($backups.Count -gt 0) {
                $mostRecentBackup = $backups[0].FullName
                if ($PSCmdlet.ShouldProcess("Restore $hookType from backup", "Restore")) {
                    try {
                        Move-Item -LiteralPath $mostRecentBackup -Destination $hookPath -Force
                        $results.Restored += @{
                            HookType = $hookType
                            BackupUsed = $mostRecentBackup
                        }

                        if (-not $KeepBackup) {
                            # Remove older backups
                            $backups | Select-Object -Skip 1 | Remove-Item -Force -ErrorAction SilentlyContinue
                        }

                        Write-GitHookLog -HookType $hookType -Action 'Restore' -Status 'Success' -ProjectRoot $resolvedRoot
                    } catch {
                        $results.Failed += @{
                            HookType = $hookType
                            Reason = "Failed to restore backup: $_"
                        }
                    }
                }
            } else {
                Write-Warning "No backup found for $hookType hook."
                $results.Failed += @{
                    HookType = $hookType
                    Reason = "No backup found"
                }
            }
        } else {
            if ($PSCmdlet.ShouldProcess("Remove $hookType hook", "Remove")) {
                try {
                    Remove-Item -LiteralPath $hookPath -Force
                    $results.Removed += $hookType

                    Write-GitHookLog -HookType $hookType -Action 'Uninstall' -Status 'Success' -ProjectRoot $resolvedRoot
                } catch {
                    $results.Failed += @{
                        HookType = $hookType
                        Reason = $_.Exception.Message
                    }
                }
            }
        }
    }

    return [PSCustomObject]@{
        ProjectRoot = $resolvedRoot
        RemovedCount = $results.Removed.Count
        RestoredCount = $results.Restored.Count
        FailedCount = $results.Failed.Count
        Removed = $results.Removed
        Restored = $results.Restored
        NotFound = $results.NotFound
        Failed = $results.Failed
    }
}

#===============================================================================
# Hook Validation Functions
#===============================================================================

function Test-GitHookConfiguration {
    <#
    .SYNOPSIS
        Validates the Git hook setup for LLM Workflow.

    .DESCRIPTION
        Checks which hooks are installed, verifies hook scripts are current,
        and reports the complete configuration status.

    .PARAMETER ProjectRoot
        Path to the project root. Defaults to current directory.

    .PARAMETER VerifyContent
        If specified, verifies that installed hooks have valid content.

    .EXAMPLE
        Test-GitHookConfiguration
        Returns the status of all Git hooks for the current project.

    .OUTPUTS
        PSCustomObject with detailed hook configuration status.
    #>
    [CmdletBinding()]
    param(
        [Parameter()]
        [string]$ProjectRoot = '.',

        [Parameter()]
        [switch]$VerifyContent
    )

    # Resolve project root
    $resolvedRoot = Resolve-Path -LiteralPath $ProjectRoot -ErrorAction SilentlyContinue
    if (-not $resolvedRoot) {
        throw "Project root does not exist: $ProjectRoot"
    }
    $resolvedRoot = $resolvedRoot.Path

    $hooksDir = Join-Path $resolvedRoot '.git' 'hooks'
    $hasGitDir = Test-Path -LiteralPath (Join-Path $resolvedRoot '.git')
    $hasHooksDir = Test-Path -LiteralPath $hooksDir

    $hookStatuses = @()
    foreach ($hookType in $script:ValidHookTypes) {
        $hookPath = Join-Path $hooksDir $hookType
        $exists = Test-Path -LiteralPath $hookPath
        $isLLMWorkflowHook = $false
        $isCurrent = $false
        $issues = @()

        if ($exists) {
            $content = Get-Content -LiteralPath $hookPath -Raw -ErrorAction SilentlyContinue
            $isLLMWorkflowHook = $content -and ($content -match 'LLM Workflow Git Hook')

            if ($VerifyContent -and $isLLMWorkflowHook) {
                # Verify the hook has valid content structure
                $isCurrent = ($content -match 'Import-Module LLMWorkflow') -and
                           ($content -match 'Invoke-GitHook')

                if (-not $isCurrent) {
                    $issues += "Hook content may be outdated"
                }
            }

            # Check executable permissions on Unix
            if (-not ($IsWindows -or ($PSVersionTable.PSVersion.Major -lt 6))) {
                $permissions = & stat -c %a $hookPath 2>$null
                if ($permissions -and -not ($permissions -match '^[75]')) {
                    $issues += "Hook may not be executable (permissions: $permissions)"
                }
            }
        }

        $hookStatuses += [PSCustomObject]@{
            HookType = $hookType
            Installed = $exists
            IsLLMWorkflowHook = $isLLMWorkflowHook
            IsCurrent = if ($VerifyContent) { $isCurrent } else { $null }
            Path = if ($exists) { $hookPath } else { $null }
            Issues = $issues
        }
    }

    # Check for global hooks
    $globalHooksPath = & git config --global core.hooksPath 2>$null

    return [PSCustomObject]@{
        ProjectRoot = $resolvedRoot
        HasGitRepository = $hasGitDir
        HasHooksDirectory = $hasHooksDir
        HooksDirectory = if ($hasHooksDir) { $hooksDir } else { $null }
        GlobalHooksPath = $globalHooksPath
        Hooks = $hookStatuses
        Summary = @{
            Total = $script:ValidHookTypes.Count
            Installed = ($hookStatuses | Where-Object { $_.Installed }).Count
            LLMWorkflowHooks = ($hookStatuses | Where-Object { $_.IsLLMWorkflowHook }).Count
            IssuesFound = ($hookStatuses | Where-Object { $_.Issues.Count -gt 0 }).Count
        }
    }
}

#===============================================================================
# Hook Execution Functions
#===============================================================================

function Invoke-GitHookPreCommit {
    <#
    .SYNOPSIS
        Executes pre-commit hook logic.

    .DESCRIPTION
        Performs secret scanning, health score check, and policy validation.
        Fails the commit if critical issues are found.

    .PARAMETER ProjectRoot
        Path to the project root. Defaults to current directory.

    .PARAMETER StagedFilesOnly
        If specified, only scans staged files. Otherwise scans all modified files.

    .PARAMETER SkipSecretScan
        If specified, skips secret scanning (not recommended).

    .PARAMETER SkipHealthCheck
        If specified, skips health check.

    .PARAMETER SeverityThreshold
        Minimum severity to block commit: low, medium, high, critical.
        Defaults to critical.

    .EXAMPLE
        $result = Invoke-GitHookPreCommit
        Runs pre-commit checks and returns result object.

    .OUTPUTS
        PSCustomObject with ExitCode (0=OK, 1=Block) and check results.
    #>
    [CmdletBinding()]
    param(
        [Parameter()]
        [string]$ProjectRoot = '.',

        [Parameter()]
        [switch]$StagedFilesOnly,

        [Parameter()]
        [switch]$SkipSecretScan,

        [Parameter()]
        [switch]$SkipHealthCheck,

        [Parameter()]
        [ValidateSet('low', 'medium', 'high', 'critical')]
        [string]$SeverityThreshold = 'critical'
    )

    $startTime = Get-Date
    $exitCode = 0
    $findings = @()
    $messages = @()

    # Get current execution mode
    $executionMode = Get-CurrentExecutionMode
    $isCI = ($executionMode -eq 'ci') -or ($env:CI -eq 'true')

    try {
        # Get files to scan
        $filesToScan = @()
        if ($StagedFilesOnly) {
            $stagedOutput = & git diff --cached --name-only --diff-filter=ACM 2>$null
            if ($stagedOutput) {
                $filesToScan = $stagedOutput -split "`n" | Where-Object { $_ }
            }
        } else {
            $modifiedOutput = & git diff --name-only --diff-filter=ACM 2>$null
            if ($modifiedOutput) {
                $filesToScan = $modifiedOutput -split "`n" | Where-Object { $_ }
            }
        }

        # Secret Scanning
        if (-not $SkipSecretScan) {
            Write-Verbose "[PreCommit] Scanning for secrets..."
            $secretFindings = @()

            foreach ($file in $filesToScan) {
                $filePath = Join-Path $ProjectRoot $file
                if (Test-Path -LiteralPath $filePath -PathType Leaf) {
                    try {
                        $content = Get-Content -LiteralPath $filePath -Raw -ErrorAction SilentlyContinue
                        if ($content) {
                            $scanResult = Test-SecretInContent -Content $content -SeverityThreshold $SeverityThreshold
                            if ($scanResult.HasSecrets) {
                                $criticalCount = ($scanResult.Findings | Where-Object { $_.Severity -eq 'critical' }).Count
                                $secretFindings += @{
                                    File = $file
                                    Findings = $scanResult.Findings
                                    CriticalCount = $criticalCount
                                }
                            }
                        }
                    } catch {
                        Write-Verbose "[PreCommit] Failed to scan file $file : $_"
                    }
                }
            }

            if ($secretFindings.Count -gt 0) {
                $totalCritical = ($secretFindings | Measure-Object -Property CriticalCount -Sum).Sum
                if ($totalCritical -gt 0) {
                    $exitCode = 1
                    $messages += "CRITICAL: Found $totalCritical critical secrets in staged files"
                }
                $findings += @{
                    Check = 'SecretScan'
                    Status = if ($totalCritical -gt 0) { 'Failed' } else { 'Warning' }
                    Details = $secretFindings
                }
            } else {
                $findings += @{
                    Check = 'SecretScan'
                    Status = 'Passed'
                    Details = $null
                }
            }
        }

        # Health Check
        if (-not $SkipHealthCheck -and $exitCode -eq 0) {
            Write-Verbose "[PreCommit] Running health check..."
            # Quick health check - verify critical components
            $healthIssues = @()

            # Check .env file exists and has required keys
            $envPath = Join-Path $ProjectRoot '.env'
            if (-not (Test-Path -LiteralPath $envPath)) {
                $healthIssues += "Missing .env file"
            }

            # Check for pack manifest validity
            $manifestDir = Join-Path $ProjectRoot 'packs' 'manifests'
            if (Test-Path -LiteralPath $manifestDir) {
                $manifests = Get-ChildItem -Path $manifestDir -Filter '*.json' -ErrorAction SilentlyContinue
                foreach ($manifest in $manifests) {
                    try {
                        $content = Get-Content -LiteralPath $manifest.FullName -Raw | ConvertFrom-Json
                        # Basic validation
                        if (-not $content.packId -or -not $content.version) {
                            $healthIssues += "Invalid manifest: $($manifest.Name)"
                        }
                    } catch {
                        $healthIssues += "Corrupted manifest: $($manifest.Name)"
                    }
                }
            }

            if ($healthIssues.Count -gt 0) {
                $findings += @{
                    Check = 'HealthCheck'
                    Status = 'Warning'
                    Details = $healthIssues
                }
                $messages += "Health check warnings: $($healthIssues -join ', ')"
            } else {
                $findings += @{
                    Check = 'HealthCheck'
                    Status = 'Passed'
                    Details = $null
                }
            }
        }

        # Policy Validation
        $policy = Get-PolicyRules
        if ($policy -and $policy.rules) {
            $currentMode = Get-CurrentExecutionMode
            # Check if commits are allowed in current mode
            $allowed = Test-PolicyPermission -Command 'commit' -Mode $currentMode -Policy $policy
            if (-not $allowed) {
                $exitCode = 1
                $findings += @{
                    Check = 'Policy'
                    Status = 'Failed'
                    Details = "Commits not allowed in $currentMode mode"
                }
                $messages += "Policy violation: Commits blocked in $currentMode mode"
            } else {
                $findings += @{
                    Check = 'Policy'
                    Status = 'Passed'
                    Details = $null
                }
            }
        }

    } catch {
        $exitCode = 1
        $messages += "Error during pre-commit: $_"
        $findings += @{
            Check = 'Error'
            Status = 'Failed'
            Details = $_.Exception.Message
        }
    }

    $duration = ((Get-Date) - $startTime).TotalSeconds

    # Log the hook execution
    Write-GitHookLog -HookType 'pre-commit' -Action 'Execute' -Status $(if ($exitCode -eq 0) { 'Success' } else { 'Blocked' }) `
        -ProjectRoot $ProjectRoot -Details "Duration: ${duration}s, Files: $($filesToScan.Count)"

    # Output messages in interactive mode
    if (-not $isCI -and $messages.Count -gt 0) {
        foreach ($msg in $messages) {
            if ($msg -match '^CRITICAL') {
                Write-Host $msg -ForegroundColor Red
            } elseif ($msg -match '^Warning') {
                Write-Warning $msg
            } else {
                Write-Host $msg
            }
        }
    }

    return [PSCustomObject]@{
        ExitCode = $exitCode
        Success = ($exitCode -eq 0)
        Duration = $duration
        FilesScanned = $filesToScan.Count
        Findings = $findings
        Messages = $messages
    }
}

function Invoke-GitHookPostCommit {
    <#
    .SYNOPSIS
        Executes post-commit hook logic.

    .DESCRIPTION
        Queues sync for affected sources, updates sync state.
        This hook is non-blocking and always returns success.

    .PARAMETER ProjectRoot
        Path to the project root. Defaults to current directory.

    .PARAMETER SkipSync
        If specified, skips the auto-sync operation.

    .EXAMPLE
        Invoke-GitHookPostCommit
        Runs post-commit operations.

    .OUTPUTS
        PSCustomObject with operation results.
    #>
    [CmdletBinding()]
    param(
        [Parameter()]
        [string]$ProjectRoot = '.',

        [Parameter()]
        [switch]$SkipSync
    )

    $startTime = Get-Date
    $messages = @()
    $syncQueued = $false

    try {
        # Get commit info
        $commitHash = & git rev-parse HEAD 2>$null
        $commitMsg = & git log -1 --pretty=%B 2>$null
        $changedFiles = & git diff-tree --no-commit-id --name-only -r HEAD 2>$null

        if ($changedFiles) {
            $affectedFiles = $changedFiles -split "`n" | Where-Object { $_ }

            # Check if any pack files were modified
            $packFiles = $affectedFiles | Where-Object { $_ -like 'packs/*' -or $_ -like '.memorybridge/*' }

            if ($packFiles.Count -gt 0 -and -not $SkipSync) {
                # Queue sync for affected sources (non-blocking)
                $syncStatePath = Join-Path $ProjectRoot '.memorybridge' 'sync-queue.json'
                $syncEntry = @{
                    timestamp = [DateTime]::UtcNow.ToString("o")
                    commitHash = $commitHash
                    affectedFiles = $packFiles
                    status = 'pending'
                }

                # Ensure directory exists
                $syncDir = Split-Path -Parent $syncStatePath
                if (-not (Test-Path -LiteralPath $syncDir)) {
                    New-Item -ItemType Directory -Path $syncDir -Force | Out-Null
                }

                # Append to queue
                $syncEntry | ConvertTo-Json -Compress | Add-Content -LiteralPath $syncStatePath -ErrorAction SilentlyContinue
                $syncQueued = $true
                $messages += "Queued sync for $($packFiles.Count) pack files"
            }

            # Update sync state if it exists
            $syncStateFile = Join-Path $ProjectRoot '.memorybridge' 'sync-state.json'
            if (Test-Path -LiteralPath $syncStateFile) {
                try {
                    $state = Get-Content -LiteralPath $syncStateFile -Raw | ConvertFrom-Json
                    $state | Add-Member -NotePropertyName 'lastCommit' -NotePropertyValue $commitHash -Force
                    $state | Add-Member -NotePropertyName 'lastCommitTime' -NotePropertyValue ([DateTime]::UtcNow.ToString("o")) -Force
                    $state | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $syncStateFile -Force
                } catch {
                    Write-Verbose "[PostCommit] Failed to update sync state: $_"
                }
            }
        }

        $messages += "Post-commit processing complete"

    } catch {
        # Post-commit is non-blocking, just log errors
        $messages += "Warning during post-commit: $_"
    }

    $duration = ((Get-Date) - $startTime).TotalSeconds

    # Log the hook execution
    Write-GitHookLog -HookType 'post-commit' -Action 'Execute' -Status 'Success' `
        -ProjectRoot $ProjectRoot -Details "Duration: ${duration}s, SyncQueued: $syncQueued"

    return [PSCustomObject]@{
        ExitCode = 0  # Post-commit is always non-blocking
        Success = $true
        Duration = $duration
        SyncQueued = $syncQueued
        Messages = $messages
    }
}

function Invoke-GitHookPrePush {
    <#
    .SYNOPSIS
        Executes pre-push hook logic.

    .DESCRIPTION
        Performs full health check, compatibility validation, and pack validation.
        Fails the push if critical issues are found.

    .PARAMETER ProjectRoot
        Path to the project root. Defaults to current directory.

    .PARAMETER RemoteName
        Name of the remote being pushed to.

    .PARAMETER RemoteUrl
        URL of the remote being pushed to.

    .PARAMETER SkipHealthCheck
        If specified, skips the health check.

    .PARAMETER SkipCompatibilityCheck
        If specified, skips compatibility validation.

    .EXAMPLE
        Invoke-GitHookPrePush -RemoteName 'origin' -RemoteUrl 'https://github.com/user/repo.git'
        Runs pre-push validation.

    .OUTPUTS
        PSCustomObject with ExitCode (0=OK, 1=Block) and validation results.
    #>
    [CmdletBinding()]
    param(
        [Parameter()]
        [string]$ProjectRoot = '.',

        [Parameter()]
        [string]$RemoteName = 'origin',

        [Parameter()]
        [string]$RemoteUrl = '',

        [Parameter()]
        [switch]$SkipHealthCheck,

        [Parameter()]
        [switch]$SkipCompatibilityCheck
    )

    $startTime = Get-Date
    $exitCode = 0
    $findings = @()
    $messages = @()

    # Get current execution mode
    $executionMode = Get-CurrentExecutionMode
    $isCI = ($executionMode -eq 'ci') -or ($env:CI -eq 'true')

    try {
        # Full Health Check
        if (-not $SkipHealthCheck) {
            Write-Verbose "[PrePush] Running full health check..."

            # Check all issue types
            $issueTypes = @('MissingEnvFile', 'InvalidPythonPath', 'MissingBridgeConfig', 
                          'CorruptedBridgeConfig', 'CorruptedSyncState')

            $healthIssues = @()
            foreach ($issueType in $issueTypes) {
                try {
                    $issueCheck = Test-LLMWorkflowIssue -IssueType $issueType -ProjectRoot $ProjectRoot
                    if ($issueCheck.Detected -and $issueCheck.Category -eq 'CRITICAL') {
                        $healthIssues += "$issueType : $($issueCheck.Message)"
                    }
                } catch {
                    Write-Verbose "[PrePush] Failed to check $issueType : $_"
                }
            }

            if ($healthIssues.Count -gt 0) {
                $exitCode = 1
                $findings += @{
                    Check = 'HealthCheck'
                    Status = 'Failed'
                    Details = $healthIssues
                }
                $messages += "CRITICAL: Health check failed with $($healthIssues.Count) critical issues"
            } else {
                $findings += @{
                    Check = 'HealthCheck'
                    Status = 'Passed'
                    Details = $null
                }
            }
        }

        # Compatibility Validation
        if (-not $SkipCompatibilityCheck -and $exitCode -eq 0) {
            Write-Verbose "[PrePush] Checking compatibility..."

            # Check compatibility.lock.json
            $compatPath = Join-Path $ProjectRoot 'compatibility.lock.json'
            if (Test-Path -LiteralPath $compatPath) {
                try {
                    $compat = Get-Content -LiteralPath $compatPath -Raw | ConvertFrom-Json
                    $currentVersion = (Get-LLMWorkflowVersion).Version

                    # Verify version compatibility
                    if ($compat.minVersion -and ([version]$currentVersion -lt [version]$compat.minVersion)) {
                        $exitCode = 1
                        $findings += @{
                            Check = 'Compatibility'
                            Status = 'Failed'
                            Details = "Current version $currentVersion is below minimum required $($compat.minVersion)"
                        }
                        $messages += "CRITICAL: Version compatibility check failed"
                    } else {
                        $findings += @{
                            Check = 'Compatibility'
                            Status = 'Passed'
                            Details = $compat
                        }
                    }
                } catch {
                    $findings += @{
                        Check = 'Compatibility'
                        Status = 'Warning'
                        Details = "Failed to read compatibility.lock.json: $_"
                    }
                }
            } else {
                $findings += @{
                    Check = 'Compatibility'
                    Status = 'Warning'
                    Details = "No compatibility.lock.json found"
                }
            }
        }

        # Pack Validation
        if ($exitCode -eq 0) {
            Write-Verbose "[PrePush] Validating packs..."

            $manifestDir = Join-Path $ProjectRoot 'packs' 'manifests'
            $packIssues = @()

            if (Test-Path -LiteralPath $manifestDir) {
                $manifests = Get-ChildItem -Path $manifestDir -Filter '*.json' -ErrorAction SilentlyContinue
                foreach ($manifest in $manifests) {
                    try {
                        $content = Get-Content -LiteralPath $manifest.FullName -Raw | ConvertFrom-Json -AsHashtable
                        $validation = Test-PackManifest -Manifest $content
                        if (-not $validation.isValid) {
                            $packIssues += "$($manifest.Name): $($validation.errors -join ', ')"
                        }
                    } catch {
                        $packIssues += "$($manifest.Name): Invalid JSON"
                    }
                }
            }

            if ($packIssues.Count -gt 0) {
                $exitCode = 1
                $findings += @{
                    Check = 'PackValidation'
                    Status = 'Failed'
                    Details = $packIssues
                }
                $messages += "CRITICAL: Pack validation failed with $($packIssues.Count) issues"
            } else {
                $findings += @{
                    Check = 'PackValidation'
                    Status = 'Passed'
                    Details = $null
                }
            }
        }

        # Secret Scan (comprehensive on all files to be pushed)
        if ($exitCode -eq 0) {
            Write-Verbose "[PrePush] Scanning for secrets in push..."

            # Get commits being pushed
            $localRef = $env:LOCAL_REF
            $remoteRef = $env:REMOTE_REF

            if ($localRef -and $remoteRef) {
                $commits = & git rev-list "$remoteRef..$localRef" 2>$null
                $secretFound = $false

                foreach ($commit in $commits) {
                    $files = & git diff-tree --no-commit-id --name-only -r $commit 2>$null
                    foreach ($file in $files) {
                        $content = & git show "$commit`:$file" 2>$null
                        if ($content) {
                            $scanResult = Test-SecretInContent -Content $content -SeverityThreshold 'critical'
                            if ($scanResult.HasSecrets) {
                                $criticalCount = ($scanResult.Findings | Where-Object { $_.Severity -eq 'critical' }).Count
                                if ($criticalCount -gt 0) {
                                    $secretFound = $true
                                    break
                                }
                            }
                        }
                    }
                    if ($secretFound) { break }
                }

                if ($secretFound) {
                    $exitCode = 1
                    $findings += @{
                        Check = 'SecretScan'
                        Status = 'Failed'
                        Details = "Critical secrets found in commits to be pushed"
                    }
                    $messages += "CRITICAL: Secrets detected in push commits"
                } else {
                    $findings += @{
                        Check = 'SecretScan'
                        Status = 'Passed'
                        Details = $null
                    }
                }
            }
        }

    } catch {
        $exitCode = 1
        $messages += "Error during pre-push: $_"
        $findings += @{
            Check = 'Error'
            Status = 'Failed'
            Details = $_.Exception.Message
        }
    }

    $duration = ((Get-Date) - $startTime).TotalSeconds

    # Log the hook execution
    Write-GitHookLog -HookType 'pre-push' -Action 'Execute' -Status $(if ($exitCode -eq 0) { 'Success' } else { 'Blocked' }) `
        -ProjectRoot $ProjectRoot -Details "Duration: ${duration}s, Remote: $RemoteName"

    # Output messages
    if ($messages.Count -gt 0) {
        foreach ($msg in $messages) {
            if ($msg -match '^CRITICAL') {
                if ($isCI) {
                    Write-Error $msg
                } else {
                    Write-Host $msg -ForegroundColor Red
                }
            } elseif ($msg -match '^Warning') {
                Write-Warning $msg
            } else {
                Write-Verbose $msg
            }
        }
    }

    return [PSCustomObject]@{
        ExitCode = $exitCode
        Success = ($exitCode -eq 0)
        Duration = $duration
        RemoteName = $RemoteName
        RemoteUrl = $RemoteUrl
        Findings = $findings
        Messages = $messages
    }
}

#===============================================================================
# Hook Script Generation
#===============================================================================

function New-GitHookScript {
    <#
    .SYNOPSIS
        Generates Git hook script content.

    .DESCRIPTION
        Creates PowerShell-based hook scripts with cross-platform support
        and proper error handling.

    .PARAMETER HookType
        The type of hook to generate: pre-commit, post-commit, pre-push, post-merge.

    .PARAMETER ProjectRoot
        Path to the project root for resolving relative paths.

    .PARAMETER CustomLogic
        Optional custom PowerShell code to include in the hook.

    .EXAMPLE
        $script = New-GitHookScript -HookType 'pre-commit'
        Generates a pre-commit hook script.

    .OUTPUTS
        String containing the hook script content.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateSet('pre-commit', 'post-commit', 'pre-push', 'post-merge')]
        [string]$HookType,

        [Parameter()]
        [string]$ProjectRoot = '.',

        [Parameter()]
        [string]$CustomLogic = ''
    )

    # Generate header with timestamp
    $header = $script:HookScriptHeader -f ([DateTime]::UtcNow.ToString("o"))

    # Generate hook-specific logic
    $hookLogic = switch ($HookType) {
        'pre-commit' {
            @'
# Pre-commit: Secret scanning and health check
$result = Invoke-GitHookPreCommit -ProjectRoot $PSScriptRoot/.. -StagedFilesOnly
'@
        }
        'post-commit' {
            @'
# Post-commit: Auto-sync (non-blocking)
$result = Invoke-GitHookPostCommit -ProjectRoot $PSScriptRoot/..
'@
        }
        'pre-push' {
            @'
# Pre-push: Full validation
# Read push arguments from stdin
$pushArgs = @()
while ($line = [Console]::In.ReadLine()) {
    if ([string]::IsNullOrWhiteSpace($line)) { break }
    $pushArgs += $line
}

# Parse remote info
$remoteName = $args[0]
$remoteUrl = $args[1]

$result = Invoke-GitHookPrePush -ProjectRoot $PSScriptRoot/.. -RemoteName $remoteName -RemoteUrl $remoteUrl
'@
        }
        'post-merge' {
            @'
# Post-merge: Rebuild affected packs
$isSquash = $args[0] -eq '1'

# Get merge commit info
$mergeCommit = & git rev-parse HEAD
$parents = & git rev-parse HEAD^@ 2>$null

if ($parents.Count -eq 2) {
    # Regular merge - check what changed
    $changedFiles = & git diff-tree --no-commit-id --name-only -r $mergeCommit
    
    # Check for pack changes
    $packChanges = $changedFiles | Where-Object { $_ -like 'packs/*' }
    if ($packChanges) {
        Write-Host "[LLM Workflow] Pack changes detected in merge. Consider rebuilding packs." -ForegroundColor Cyan
    }
}

$result = [PSCustomObject]@{
    ExitCode = 0
    Success = $true
}
'@
        }
        default {
            @'
# Unknown hook type - exit cleanly
$result = [PSCustomObject]@{
    ExitCode = 0
    Success = $true
}
'@
        }
    }

    # Add custom logic if provided
    if ($CustomLogic) {
        $hookLogic += "`n# Custom logic`n$CustomLogic"
    }

    # Combine all parts
    $scriptContent = @($header, $hookLogic, $script:HookScriptFooter) -join "`n"

    return $scriptContent
}

#===============================================================================
# Helper Functions
#===============================================================================

function Write-GitHookLog {
    <#
    .SYNOPSIS
        Writes a structured log entry for Git hook operations.

    .DESCRIPTION
        Internal function for logging hook events using the structured logging system.

    .PARAMETER HookType
        The type of hook.

    .PARAMETER Action
        The action performed (Install, Uninstall, Execute, etc.).

    .PARAMETER Status
        The status of the action.

    .PARAMETER ProjectRoot
        Path to the project root.

    .PARAMETER Details
        Additional details about the operation.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$HookType,

        [Parameter(Mandatory = $true)]
        [string]$Action,

        [Parameter(Mandatory = $true)]
        [string]$Status,

        [Parameter()]
        [string]$ProjectRoot = '.',

        [Parameter()]
        [string]$Details = ''
    )

    try {
        # Check if logging function is available
        $logCmd = Get-Command New-LogEntry -ErrorAction SilentlyContinue
        if (-not $logCmd) {
            # Fall back to verbose output
            Write-Verbose "[GitHook] $HookType - $Action : $Status"
            return
        }

        $metadata = @{
            hookType = $HookType
            action = $Action
            projectRoot = $ProjectRoot
            details = $Details
        }

        $entry = New-LogEntry -Level 'INFO' -Message "Git hook $Action : $Status" `
            -Source 'GitHooks' -Metadata $metadata

        # Try to write structured log
        $writeCmd = Get-Command Write-StructuredLog -ErrorAction SilentlyContinue
        if ($writeCmd) {
            $entry | Write-StructuredLog -Force
        }
    } catch {
        # Silent failure for logging
        Write-Verbose "[GitHook] Failed to write log: $_"
    }
}

#===============================================================================
# Module Export Note
#===============================================================================

# Export-ModuleMember is handled by LLMWorkflow.psm1
# Functions exported: All public functions in this file
