#requires -Version 5.1
Set-StrictMode -Version Latest
<#
.SYNOPSIS
    Pack and workspace health scoring.
.DESCRIPTION
    PowerShell 5.1-safe health scoring and report export. JSON is converted through local helpers instead of using PS7-only switches.
#>
$script:ScoreWeights = @{ SourceRegistryComplete = 20; StaleSourcePenalty = -10; FailedExtractionPenalty = -15; MissingLockfilePenalty = -20; OutdatedLockfilePenalty = -10; ValidationErrorPenalty = -5; MaxScore = 100; MinScore = 0 }
$script:StatusThresholds = @{ Healthy = 80; Degraded = 60 }
$script:LockfileStaleDays = 30
function ConvertTo-PackHealthHashtable { [CmdletBinding()] param([Parameter(ValueFromPipeline)]$InputObject) process { if ($null -eq $InputObject) { return $null }; if ($InputObject -is [hashtable]) { return $InputObject }; if ($InputObject -is [System.Collections.IDictionary]) { $h=@{}; foreach($k in $InputObject.Keys){$h[$k]=ConvertTo-PackHealthHashtable $InputObject[$k]}; return $h }; if ($InputObject -is [System.Collections.IEnumerable] -and -not ($InputObject -is [string])) { return @($InputObject | ForEach-Object { ConvertTo-PackHealthHashtable $_ }) }; if ($InputObject.GetType().Name -eq 'PSCustomObject') { $h=@{}; foreach($p in $InputObject.PSObject.Properties){$h[$p.Name]=ConvertTo-PackHealthHashtable $p.Value}; return $h }; $InputObject } }
function Read-PackHealthJson { [CmdletBinding()] param([Parameter(Mandatory)][string]$Path) ConvertTo-PackHealthHashtable (Get-Content -LiteralPath $Path -Raw -ErrorAction Stop | ConvertFrom-Json) }
function Get-PackHealthObjectProperty { param([object]$InputObject,[string]$Name,[object]$Default=$null) if($null -eq $InputObject){return $Default}; if($InputObject -is [hashtable]){if($InputObject.ContainsKey($Name) -and $null -ne $InputObject[$Name]){return $InputObject[$Name]}; return $Default}; $p=$InputObject.PSObject.Properties[$Name]; if($p -and $null -ne $p.Value){return $p.Value}; $Default }
function New-PackHealthRunId { try { & "$PSScriptRoot/../core/RunId.ps1" -Command Get-CurrentRunId } catch { try { & "$PSScriptRoot/../core/RunId.ps1" -Command New-RunId } catch { [guid]::NewGuid().ToString('N') } } }
function Get-PackHealthScore {
    [CmdletBinding()] [OutputType([hashtable])]
    param([Parameter(Mandatory)][ValidatePattern('^[a-z0-9-]+$')][string]$PackId,[string]$ManifestPath,[string]$SourceRegistryPath,[string]$LockfilePath,[switch]$Explain,[string]$RunId)
    if(-not $RunId){$RunId=New-PackHealthRunId}; if(-not $ManifestPath){$ManifestPath="packs/manifests/$PackId.json"}; if(-not $SourceRegistryPath){$SourceRegistryPath="packs/registries/$PackId.sources.json"}; if(-not $LockfilePath){$LockfilePath="packs/locks/$PackId.lock.json"}
    $score=100; $deductions=@(); $components=@{}; $raw=@{}; $notes=@(); $registry=$null
    if(Test-Path -LiteralPath $SourceRegistryPath){try{$registry=Read-PackHealthJson $SourceRegistryPath; $sources=$registry.sources; $total=if($sources){$sources.Count}else{0}; $active=if($sources){@($sources.GetEnumerator()|Where-Object{$_.Value.state -eq 'active'}).Count}else{0}; if($total -eq 0){$score-=10; $deductions+='Source registry is empty'}; $components.sources=if($total -gt 0){20}else{10}; $raw.totalSources=$total; $raw.activeSources=$active}catch{$score-=20; $components.sources=0; $deductions+='Source registry could not be read'}}else{$score-=20; $components.sources=0; $deductions+="Source registry file not found: $SourceRegistryPath"; $raw.totalSources=0; $raw.activeSources=0}
    $stale=0; $extract=0
    if($registry -and $registry.sources){foreach($entry in $registry.sources.GetEnumerator()){$src=$entry.Value; if((Get-PackHealthObjectProperty $src 'state' 'active') -ne 'active'){continue}; $id=Get-PackHealthObjectProperty $src 'sourceId' $entry.Key; $last=Get-PackHealthObjectProperty $src 'lastExtractedUtc' $null; if(-not $last){$last=Get-PackHealthObjectProperty $src 'lastReviewedUtc' $null}; if(-not $last){$last=Get-PackHealthObjectProperty $src 'updatedUtc' $null}; if($last){$age=([DateTime]::UtcNow-[DateTime]::Parse($last)).TotalDays; if($age -gt 30){$stale++; $deductions+="Stale source '$id'"}}else{$stale++; $deductions+="Source '$id' has no freshness date"}; if((Get-PackHealthObjectProperty $src 'extractionStatus' '') -eq 'failed'){$extract++; $deductions+="Extraction failed for source '$id'"}; $extract += [int](Get-PackHealthObjectProperty $src 'extractionErrors' 0)}}
    $score += $stale*$script:ScoreWeights.StaleSourcePenalty; $score += $extract*$script:ScoreWeights.FailedExtractionPenalty; $components.freshness=[math]::Max(0,20+($stale*$script:ScoreWeights.StaleSourcePenalty)); $components.extraction=[math]::Max(0,20+($extract*$script:ScoreWeights.FailedExtractionPenalty)); $raw.staleSources=$stale; $raw.failedExtractions=$extract
    if(Test-Path -LiteralPath $LockfilePath){try{$lock=Read-PackHealthJson $LockfilePath; $raw.lockfileStatus='present'; if($lock.generatedUtc){$age=([DateTime]::UtcNow-[DateTime]::Parse($lock.generatedUtc)).TotalDays; $raw.lockfileAgeDays=$age; if($age -gt $script:LockfileStaleDays){$score+=$script:ScoreWeights.OutdatedLockfilePenalty; $raw.lockfileStatus='outdated'; $deductions+='Lockfile is outdated'}}}catch{$score+=$script:ScoreWeights.MissingLockfilePenalty; $raw.lockfileStatus='invalid'; $deductions+='Lockfile could not be read'}}else{$score+=$script:ScoreWeights.MissingLockfilePenalty; $raw.lockfileStatus='missing'; $deductions+="Lockfile not found: $LockfilePath"}; $components.lockfile=if($raw.lockfileStatus -eq 'present'){20}else{0}
    $val=0; if(Test-Path -LiteralPath $ManifestPath){try{$manifest=Read-PackHealthJson $ManifestPath; foreach($f in @('packId','domain','version')){if(-not (Get-PackHealthObjectProperty $manifest $f $null)){$val++; $deductions+="Manifest missing $f"}}}catch{$val++; $deductions+='Manifest could not be read'}}else{$val++; $deductions+="Manifest file not found: $ManifestPath"}
    $score += $val*$script:ScoreWeights.ValidationErrorPenalty; $components.validation=[math]::Max(0,20+($val*$script:ScoreWeights.ValidationErrorPenalty)); $raw.validationErrors=$val
    $final=[math]::Max(0,[math]::Min(100,$score)); $result=@{packId=$PackId;score=$final;runId=$RunId;generatedUtc=[DateTime]::UtcNow.ToString('o');components=$components;deductions=$deductions;rawMetrics=$raw}; if($Explain){$result.explanation=@{baseScore=100;calculations=$notes;finalScore=$final}}; $result
}
function Test-PackHealth { [CmdletBinding()] [OutputType([hashtable])] param([Parameter(Mandatory)][ValidatePattern('^[a-z0-9-]+$')][string]$PackId,[string]$ManifestPath,[string]$SourceRegistryPath,[string]$LockfilePath,[string]$RunId) $s=Get-PackHealthScore -PackId $PackId -ManifestPath $ManifestPath -SourceRegistryPath $SourceRegistryPath -LockfilePath $LockfilePath -RunId $RunId; $status=if($s.score -ge 80){'Healthy'}elseif($s.score -ge 60){'Degraded'}else{'Critical'}; $severity=if($status -eq 'Healthy'){'OK'}elseif($status -eq 'Degraded'){'Warning'}else{'Critical'}; $critical=@($s.deductions|Where-Object{$_ -match 'missing|not found|failed|invalid|unreadable|could not'}); $warnings=@($s.deductions|Where-Object{$critical -notcontains $_}); @{schemaVersion=1;packId=$PackId;runId=$s.runId;generatedUtc=[DateTime]::UtcNow.ToString('o');overallScore=$s.score;status=$status;severity=$severity;components=$s.components;rawMetrics=$s.rawMetrics;warnings=$warnings;criticalIssues=$critical;recommendedActions=@();statusIndicator=(Get-HealthStatusIndicator -Score $s.score)} }
function Get-WorkspaceHealthSummary { [CmdletBinding()] [OutputType([hashtable])] param([string[]]$PackIds,[switch]$IncludeDetails,[string]$RunId) if(-not $RunId){$RunId=New-PackHealthRunId}; if(-not $PackIds -and (Test-Path -LiteralPath 'packs/manifests')){$PackIds=Get-ChildItem -Path 'packs/manifests' -Filter '*.json'|ForEach-Object{try{(Read-PackHealthJson $_.FullName).packId}catch{$null}}|Where-Object{$_}}; $reports=@(); foreach($id in @($PackIds)){try{$reports+=Test-PackHealth -PackId $id -RunId $RunId}catch{$reports+=@{packId=$id;overallScore=0;status='Critical';severity='Critical';warnings=@();criticalIssues=@($_.Exception.Message)}}}; $avg=if($reports.Count){[math]::Round((($reports|ForEach-Object{$_.overallScore}|Measure-Object -Average).Average))}else{0}; $crit=@($reports|ForEach-Object{$_.criticalIssues}).Count; $overall=if($avg -ge 80 -and $crit -eq 0){'Healthy'}elseif($avg -ge 60){'Degraded'}else{'Critical'}; $summary=@{schemaVersion=1;runId=$RunId;generatedUtc=[DateTime]::UtcNow.ToString('o');activePacks=@($PackIds).Count;averageHealthScore=$avg;criticalIssuesCount=$crit;lastSyncStatus='Unknown';lastSyncTime=$null;overallStatus=$overall;statusBreakdown=@{Healthy=@($reports|Where-Object{$_.status -eq 'Healthy'}).Count;Degraded=@($reports|Where-Object{$_.status -eq 'Degraded'}).Count;Critical=@($reports|Where-Object{$_.status -eq 'Critical'}).Count}}; if($IncludeDetails){$summary.packs=$reports}; $summary }
function Export-HealthReport { [CmdletBinding()] [OutputType([string])] param([string]$OutputPath,[string[]]$PackIds,[switch]$CompareWithPrevious,[string]$RunId) if(-not $RunId){$RunId=New-PackHealthRunId}; if(-not $OutputPath){$dir='.llm-workflow/reports'; if(-not(Test-Path -LiteralPath $dir)){New-Item -ItemType Directory -Path $dir -Force|Out-Null}; $OutputPath=Join-Path $dir ("health-report-{0}.json" -f ([DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ')))}; $summary=Get-WorkspaceHealthSummary -PackIds $PackIds -IncludeDetails -RunId $RunId; $report=@{schemaVersion=1;runId=$RunId;generatedUtc=[DateTime]::UtcNow.ToString('o');overallScore=$summary.averageHealthScore;status=$summary.overallStatus;trending='stable';activePacks=$summary.activePacks;criticalIssuesCount=$summary.criticalIssuesCount;statusBreakdown=$summary.statusBreakdown;packs=$summary.packs;provenance=@{generatedBy='Export-HealthReport';version='0.4.0';runId=$RunId}}; $parent=Split-Path -Parent $OutputPath; if($parent -and -not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null}; $report|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $OutputPath -Encoding UTF8; $OutputPath }
function Get-HealthStatusIndicator { [CmdletBinding()] [OutputType([string])] param([Parameter(Mandatory)][ValidateRange(0,100)][int]$Score) if($Score -ge 90){'OK'}elseif($Score -ge 80){'Info'}elseif($Score -ge 60){'Notice'}elseif($Score -ge 40){'Warning'}else{'Critical'} }
function Get-HealthTrend { [CmdletBinding()] [OutputType([string])] param([Parameter(Mandatory)][ValidateRange(0,100)][int]$CurrentScore,[Parameter(Mandatory)][ValidateRange(0,100)][int]$PreviousScore,[int]$Threshold=5) $diff=$CurrentScore-$PreviousScore; if($diff -gt $Threshold){'improving'}elseif($diff -lt -$Threshold){'degrading'}else{'stable'} }
