#requires -Version 5.1
Set-StrictMode -Version Latest
<#
.SYNOPSIS
    PS5-safe MCP composite gateway with routing, sessions, rate limits, circuit breakers, and JSON-RPC responses.
#>
$script:GatewayState=@{isRunning=$false;startedAt=$null;gatewayId=$null;routes=@{};sessions=@{};pipelines=@{};rateLimiters=@{};circuitBreakers=@{};logs=@();config=@{defaultRateLimit=100;sessionTimeoutMinutes=30;enableFallback=$true;enableCircuitBreaker=$true;circuitBreakerThreshold=5;circuitBreakerTimeoutSeconds=30;executionMode='standard'}}
function ConvertTo-GatewayHashtable{param($InputObject) if($null -eq $InputObject){return $null}; if($InputObject -is [hashtable]){return $InputObject}; if($InputObject -is [System.Collections.IDictionary]){$h=@{}; foreach($k in $InputObject.Keys){$h[$k]=ConvertTo-GatewayHashtable $InputObject[$k]}; return $h}; if($InputObject -is [System.Collections.IEnumerable] -and -not($InputObject -is [string])){return @($InputObject|ForEach-Object{ConvertTo-GatewayHashtable $_})}; if($InputObject.GetType().Name -eq 'PSCustomObject'){$h=@{}; foreach($p in $InputObject.PSObject.Properties){$h[$p.Name]=ConvertTo-GatewayHashtable $p.Value}; return $h}; $InputObject}
function Read-GatewayJson{param([string]$Path) ConvertTo-GatewayHashtable (Get-Content -LiteralPath $Path -Raw -ErrorAction Stop|ConvertFrom-Json)}
function New-CorrelationId{[CmdletBinding()][OutputType([string])]param() [guid]::NewGuid().ToString()}
function Add-GatewayLog{param([ValidateSet('Debug','Info','Warning','Error')][string]$Level,[string]$Message,[hashtable]$Context=@{},[string]$CorrelationId='') $script:GatewayState.logs += [pscustomobject]@{timestamp=[DateTime]::UtcNow.ToString('o');level=$Level;message=$Message;context=$Context;correlationId=$CorrelationId}; if($script:GatewayState.logs.Count -gt 1000){$script:GatewayState.logs=@($script:GatewayState.logs|Select-Object -Last 1000)}}
function Write-GatewayStructuredLog{param([string]$Level,[string]$Message,[string]$CorrelationId='',[hashtable]$Metadata=@{},[System.Exception]$Exception=$null) Add-GatewayLog -Level $(if($Level -eq 'WARN'){'Warning'}elseif($Level -eq 'ERROR'){'Error'}elseif($Level -eq 'DEBUG'){'Debug'}else{'Info'}) -Message $Message -Context $Metadata -CorrelationId $CorrelationId}
function Merge-GatewayConfig{param([hashtable]$Base,[hashtable]$Override) $r=$Base.Clone(); foreach($k in $Override.Keys){if($r.ContainsKey($k)-and $r[$k] -is [hashtable] -and $Override[$k] -is [hashtable]){$r[$k]=Merge-GatewayConfig $r[$k] $Override[$k]}else{$r[$k]=$Override[$k]}}; $r}
function New-MCPCompositeGateway{[CmdletBinding()][OutputType([pscustomobject])]param([Parameter(Mandatory)][string]$Name,[hashtable]$Config=@{},[ValidateSet('round-robin','least-connections','priority')][string]$LoadBalancingStrategy='round-robin',[bool]$EnableCircuitBreaker=$true,[int]$CircuitBreakerThreshold=5,[int]$CircuitBreakerTimeoutSeconds=30,[int]$DefaultRateLimit=100,[int]$SessionTimeoutMinutes=30) $script:GatewayState.config.defaultRateLimit=$DefaultRateLimit; $script:GatewayState.config.sessionTimeoutMinutes=$SessionTimeoutMinutes; $script:GatewayState.config.enableCircuitBreaker=$EnableCircuitBreaker; $script:GatewayState.config.circuitBreakerThreshold=$CircuitBreakerThreshold; $script:GatewayState.config.circuitBreakerTimeoutSeconds=$CircuitBreakerTimeoutSeconds; [pscustomobject]@{gatewayId=New-CorrelationId;name=$Name;createdAt=[DateTime]::UtcNow.ToString('o');loadBalancingStrategy=$LoadBalancingStrategy;routes=@();customSettings=$Config}}
function Start-MCPCompositeGateway{[CmdletBinding()][OutputType([pscustomobject])]param([string]$ConfigPath='',[switch]$AutoLoadRoutes,[ValidateSet('stdio','http')][string]$Transport='stdio',[int]$Port=8080,[string]$Host='localhost',[string]$ExecutionMode='standard') if($script:GatewayState.isRunning){return Get-MCPCompositeGatewayStatus}; $script:GatewayState.isRunning=$true; $script:GatewayState.startedAt=[DateTime]::UtcNow; $script:GatewayState.gatewayId=New-CorrelationId; $script:GatewayState.transport=$Transport; $script:GatewayState.httpPort=$Port; $script:GatewayState.httpHost=$Host; $script:GatewayState.config.executionMode=$ExecutionMode; if($ConfigPath -and (Test-Path -LiteralPath $ConfigPath)){$script:GatewayState.config=Merge-GatewayConfig $script:GatewayState.config (Read-GatewayJson $ConfigPath)}; if($AutoLoadRoutes){Import-MCPRoutesFromConfig}; Initialize-RateLimiters; Initialize-CircuitBreakers; Get-MCPCompositeGatewayStatus}
function Stop-MCPCompositeGateway{[CmdletBinding()][OutputType([pscustomobject])]param([switch]$Force,[int]$TimeoutSeconds=30) $was=$script:GatewayState.isRunning; $script:GatewayState.isRunning=$false; $script:GatewayState.sessions.Clear(); [pscustomobject]@{success=$was;message=if($was){'Gateway stopped successfully'}else{'Gateway is not running'}}}
function Start-MCPGateway{[CmdletBinding()][OutputType([pscustomobject])]param([ValidateSet('stdio','http')][string]$Transport='stdio',[int]$Port=8080,[string]$Host='localhost',[switch]$AutoLoadRoutes,[string]$ConfigPath='',[string]$ExecutionMode='standard') Start-MCPCompositeGateway -Transport $Transport -Port $Port -Host $Host -AutoLoadRoutes:$AutoLoadRoutes -ConfigPath $ConfigPath -ExecutionMode $ExecutionMode}
function Stop-MCPGateway{[CmdletBinding()][OutputType([pscustomobject])]param([switch]$Force,[int]$TimeoutSeconds=30) Stop-MCPCompositeGateway -Force:$Force -TimeoutSeconds $TimeoutSeconds}
function Get-MCPCompositeGatewayStatus{[CmdletBinding()][OutputType([pscustomobject])]param() $up=if($script:GatewayState.startedAt){[DateTime]::UtcNow-$script:GatewayState.startedAt}else{[TimeSpan]::Zero}; [pscustomobject]@{isRunning=$script:GatewayState.isRunning;gatewayId=$script:GatewayState.gatewayId;uptime=$up.ToString();routeCount=$script:GatewayState.routes.Count;sessionCount=$script:GatewayState.sessions.Count;config=$script:GatewayState.config;timestamp=[DateTime]::UtcNow.ToString('o')}}
function Add-MCPPackRoute{[CmdletBinding()][OutputType([pscustomobject])]param([Parameter(Mandatory)][string]$PackId,[Parameter(Mandatory)][string]$ToolPrefix,[string]$Endpoint='stdio',[int]$Priority=1,[bool]$Enabled=$true,[int]$RateLimit=0,[string]$FallbackPackId='',[hashtable]$Metadata=@{}) $route=[pscustomobject]@{packId=$PackId;prefix=$ToolPrefix;endpoint=$Endpoint;enabled=$Enabled;rateLimit=if($RateLimit){$RateLimit}else{$script:GatewayState.config.defaultRateLimit};fallbackPackId=$FallbackPackId;priority=$Priority;metadata=$Metadata;requestCount=0;lastRequestAt=$null}; $script:GatewayState.routes[$PackId]=$route; Initialize-RateLimiter $PackId; Initialize-CircuitBreaker $PackId; $route}
function Remove-MCPPackRoute{[CmdletBinding()][OutputType([bool])]param([Parameter(Mandatory)][string]$PackId,[switch]$Force) $script:GatewayState.routes.Remove($PackId)}
function Register-MCPPackRoute{[CmdletBinding()]param([Parameter(Mandatory)][string]$PackId,[Parameter(Mandatory)][string]$ToolPrefix,[string]$Endpoint='stdio',[int]$Priority=1,[bool]$Enabled=$true,[int]$RateLimit=0,[string]$FallbackPackId='',[hashtable]$Metadata=@{}) Add-MCPPackRoute @PSBoundParameters}
function Unregister-MCPPackRoute{[CmdletBinding()]param([Parameter(Mandatory)][string]$PackId,[switch]$Force) Remove-MCPPackRoute -PackId $PackId -Force:$Force}
function Get-MCPPackRoutes{[CmdletBinding()][OutputType([array])]param([switch]$EnabledOnly,[string]$PackId='',[switch]$IncludeHealth) @($script:GatewayState.routes.Values|Where-Object{(-not $EnabledOnly -or $_.enabled) -and (-not $PackId -or $_.packId -like $PackId)})}
function Get-MCPPackRoute{[CmdletBinding()]param([Parameter(Mandatory)][string]$PackId,[switch]$IncludeHealthStatus) $script:GatewayState.routes[$PackId]}
function Ensure-GatewayRunning{if(-not $script:GatewayState.isRunning){throw 'MCP Composite Gateway is not running. Call Start-MCPCompositeGateway first.'}}
function Resolve-PackFromToolName{param([string]$ToolName) foreach($r in $script:GatewayState.routes.Values){if($r.enabled -and $ToolName.StartsWith($r.prefix)){return $r.packId}}; $null}
function Get-FallbackPack{param([string]$PackId) $r=$script:GatewayState.routes[$PackId]; if($r -and $r.fallbackPackId){$r.fallbackPackId}else{$null}}
function New-JsonRpcSuccessResponse{param($Id,$Result,[string]$CorrelationId='',[string[]]$Warnings=@()) [pscustomobject]@{jsonrpc='2.0';result=$Result;id=$Id;correlationId=$CorrelationId;warnings=$Warnings}}
function New-JsonRpcErrorResponse{param($Id,[int]$Code,[string]$Message,$Data=$null,[string]$CorrelationId='') [pscustomobject]@{jsonrpc='2.0';error=@{code=$Code;message=$Message;data=$Data};id=$Id;correlationId=$CorrelationId}}
function Invoke-ToolAtEndpoint{param([pscustomobject]$Route,[string]$ToolName,[hashtable]$Arguments=@{},[string]$SessionId='',[string]$CorrelationId='') if($Route.endpoint -eq 'stdio'){throw "No stdio adapter registered for route '$($Route.packId)' and tool '$ToolName'."}; if($Route.endpoint.StartsWith('http')){return (Invoke-RestMethod -Uri "$($Route.endpoint)/mcp/v1/tools/$ToolName" -Method Post -Body (@{jsonrpc='2.0';method='tools/call';params=@{name=$ToolName;arguments=$Arguments};id=New-CorrelationId}|ConvertTo-Json -Depth 8) -ContentType 'application/json').result}; throw "Unknown endpoint type: $($Route.endpoint)"}
function Invoke-MCPGatewayRequest{[CmdletBinding()][OutputType([pscustomobject])]param([hashtable]$Request,[string]$ToolName,[hashtable]$Arguments=@{},[string]$SessionId='',[string]$CorrelationId='',[switch]$UseFallback) Ensure-GatewayRunning; if(-not $CorrelationId){$CorrelationId=New-CorrelationId}; if($Request){$ToolName=$Request.params.name; $Arguments=$Request.params.arguments; if(-not $Arguments){$Arguments=@{}}}; $id=if($Request){$Request.id}else{New-CorrelationId}; if(-not $ToolName){return New-JsonRpcErrorResponse -Id $id -Code -32600 -Message 'Tool name is required' -CorrelationId $CorrelationId}; $pack=Resolve-PackFromToolName $ToolName; if(-not $pack){return New-JsonRpcErrorResponse -Id $id -Code -32601 -Message "No route found for tool: $ToolName" -CorrelationId $CorrelationId}; $route=$script:GatewayState.routes[$pack]; try{$result=Invoke-ToolAtEndpoint -Route $route -ToolName $ToolName -Arguments $Arguments -SessionId $SessionId -CorrelationId $CorrelationId; Record-CircuitBreakerSuccess $pack|Out-Null; New-JsonRpcSuccessResponse -Id $id -Result $result -CorrelationId $CorrelationId}catch{Record-CircuitBreakerFailure $pack $_.Exception.Message|Out-Null; New-JsonRpcErrorResponse -Id $id -Code -32603 -Message $_.Exception.Message -CorrelationId $CorrelationId}}
function Invoke-MCPPackRoute{[CmdletBinding()]param([string]$ToolName,[hashtable]$Arguments=@{},[string]$SessionId='',[string]$RequestId='') Invoke-MCPGatewayRequest -ToolName $ToolName -Arguments $Arguments -SessionId $SessionId -CorrelationId $RequestId}
function Route-MCPRequest{[CmdletBinding()]param([hashtable]$Request,[string]$SessionId='',[string]$CorrelationId='') Invoke-MCPGatewayRequest -Request $Request -SessionId $SessionId -CorrelationId $CorrelationId}
function Process-MCPGatewayRequest{[CmdletBinding()]param([hashtable]$Request,[string]$RawJson,[string]$SessionId='',[string]$CorrelationId='') if($RawJson){try{$Request=ConvertTo-GatewayHashtable ($RawJson|ConvertFrom-Json)}catch{return New-JsonRpcErrorResponse -Id $null -Code -32700 -Message $_.Exception.Message -CorrelationId $CorrelationId}}; Invoke-MCPGatewayRequest -Request $Request -SessionId $SessionId -CorrelationId $CorrelationId}
function Get-MCPGatewayManifest{[CmdletBinding()]param([switch]$IncludeMetadata,[string]$FilterPrefix='',[string]$CorrelationId='') $tools=@(); foreach($r in $script:GatewayState.routes.Values){if($FilterPrefix -and -not $r.prefix.StartsWith($FilterPrefix)){continue}; $tools+=@{name="$($r.prefix)*";packId=$r.packId;enabled=$r.enabled;endpoint=$r.endpoint}}; [pscustomobject]@{jsonrpc='2.0';result=@{tools=$tools};id=$null;correlationId=$CorrelationId}}
function Get-MCPAggregatedTools{[CmdletBinding()]param() (Get-MCPGatewayManifest).result.tools}
function Test-MCPGatewayHealth{[CmdletBinding()]param([string]$PackId='',[string]$CorrelationId='',[switch]$UpdateRouteStatus) $routes=if($PackId){@($script:GatewayState.routes[$PackId])}else{@($script:GatewayState.routes.Values)}; [pscustomobject]@{healthy=($script:GatewayState.isRunning);routes=$routes;timestamp=[DateTime]::UtcNow.ToString('o')}}
function Resolve-MCPToolTarget{[CmdletBinding()]param([string]$ToolName,[switch]$IncludeFallback) $pack=Resolve-PackFromToolName $ToolName; [pscustomobject]@{resolved=($null -ne $pack);toolName=$ToolName;primaryPack=$pack;fallbackPack=if($IncludeFallback){Get-FallbackPack $pack}else{$null}}}
function New-MCPSession{[CmdletBinding()]param([hashtable]$ContextData=@{},[int]$ExpiryMinutes=30,[hashtable]$Metadata=@{},[string]$CorrelationId='') $id=New-CorrelationId; $s=[pscustomobject]@{sessionId=$id;contextData=$ContextData;metadata=$Metadata;createdAt=[DateTime]::UtcNow;expiresAt=[DateTime]::UtcNow.AddMinutes($ExpiryMinutes);isActive=$true}; $script:GatewayState.sessions[$id]=$s; $s}
function Get-MCPSession{[CmdletBinding()]param([string]$SessionId,[switch]$IncludeInactive) if($SessionId){$script:GatewayState.sessions[$SessionId]}else{@($script:GatewayState.sessions.Values|Where-Object{$IncludeInactive -or $_.isActive})}}
function Remove-MCPSession{[CmdletBinding()]param([string]$SessionId,[switch]$Force,[string]$CorrelationId='') $script:GatewayState.sessions.Remove($SessionId)}
function Update-SessionContext{[CmdletBinding()]param([string]$SessionId,[hashtable]$ContextData,[bool]$Merge=$true,[string]$CorrelationId='') $s=$script:GatewayState.sessions[$SessionId]; if(-not $s){throw 'Session not found'}; if($Merge){foreach($k in $ContextData.Keys){$s.contextData[$k]=$ContextData[$k]}}else{$s.contextData=$ContextData}; $s}
function Initialize-RateLimiter{param([string]$PackId) $script:GatewayState.rateLimiters[$PackId]=@{tokens=$script:GatewayState.config.defaultRateLimit;lastRefill=[DateTime]::UtcNow}}
function Initialize-RateLimiters{foreach($k in $script:GatewayState.routes.Keys){Initialize-RateLimiter $k}}
function _Test-RateLimit{param([string]$PackId,[switch]$ConsumeToken) if(-not $script:GatewayState.rateLimiters[$PackId]){Initialize-RateLimiter $PackId}; $rl=$script:GatewayState.rateLimiters[$PackId]; if($ConsumeToken -and $rl.tokens -gt 0){$rl.tokens--}; @{allowed=($rl.tokens -gt 0);remaining=$rl.tokens;retryAfter=60}}
function Test-MCPRateLimit{[CmdletBinding()]param([string]$PackId,[switch]$ConsumeToken) _Test-RateLimit -PackId $PackId -ConsumeToken:$ConsumeToken}
function Get-MCPRateLimitStatus{[CmdletBinding()]param([string]$PackId='') if($PackId){$script:GatewayState.rateLimiters[$PackId]}else{$script:GatewayState.rateLimiters}}
function Initialize-CircuitBreaker{param([string]$PackId) $script:GatewayState.circuitBreakers[$PackId]=@{state='CLOSED';failureCount=0;successCount=0;lastFailureAt=$null}}
function Initialize-CircuitBreakers{foreach($k in $script:GatewayState.routes.Keys){Initialize-CircuitBreaker $k}}
function Test-CircuitBreaker{param([string]$PackId) if(-not $script:GatewayState.circuitBreakers[$PackId]){Initialize-CircuitBreaker $PackId}; $cb=$script:GatewayState.circuitBreakers[$PackId]; @{allowed=($cb.state -ne 'OPEN');state=$cb.state}}
function Test-MCPCircuitBreaker{[CmdletBinding()]param([string]$PackId) Test-CircuitBreaker $PackId}
function Record-CircuitBreakerSuccess{param([string]$PackId) if(-not $script:GatewayState.circuitBreakers[$PackId]){Initialize-CircuitBreaker $PackId}; $script:GatewayState.circuitBreakers[$PackId].successCount++; $script:GatewayState.circuitBreakers[$PackId].state='CLOSED'; $script:GatewayState.circuitBreakers[$PackId]}
function Record-CircuitBreakerFailure{param([string]$PackId,[string]$ErrorMessage='') if(-not $script:GatewayState.circuitBreakers[$PackId]){Initialize-CircuitBreaker $PackId}; $cb=$script:GatewayState.circuitBreakers[$PackId]; $cb.failureCount++; $cb.lastFailureAt=[DateTime]::UtcNow; if($cb.failureCount -ge $script:GatewayState.config.circuitBreakerThreshold){$cb.state='OPEN'}; $cb}
function Record-MCPSuccess{[CmdletBinding()]param([string]$PackId) Record-CircuitBreakerSuccess $PackId}
function Record-MCPFailure{[CmdletBinding()]param([string]$PackId,[string]$ErrorMessage='') Record-CircuitBreakerFailure $PackId $ErrorMessage}
function Reset-MCPCircuitBreaker{[CmdletBinding()]param([string]$PackId,[switch]$Force) Initialize-CircuitBreaker $PackId; $script:GatewayState.circuitBreakers[$PackId]}
function Import-MCPRoutesFromConfig{ $path=Join-Path $PWD '.llm-workflow/mcp-gateway-config.json'; if(Test-Path -LiteralPath $path){$cfg=Read-GatewayJson $path; foreach($r in @($cfg.routes)){Add-MCPPackRoute -PackId $r.packId -ToolPrefix $r.prefix -Endpoint $r.endpoint -Enabled ($r.enabled -ne $false) -RateLimit $r.rateLimit -FallbackPackId $r.fallbackPackId -Priority $r.priority|Out-Null}}}
function Invoke-MCPCrossPackQuery{[CmdletBinding()]param([string]$Query,[string[]]$TargetPacks=@(),[string]$SessionId='',[switch]$AggregateResults,[int]$MaxResultsPerPack=10,[string]$CorrelationId='') [pscustomobject]@{query=$Query;targetPacks=$TargetPacks;results=@();correlationId=$CorrelationId}}
function Invoke-MCPAggregatedTool{[CmdletBinding()]param([string]$ToolName,[hashtable]$Arguments=@{},[string]$SessionId='',[switch]$UseFallback,[int]$TimeoutSeconds=60,[string]$CorrelationId='') Invoke-MCPGatewayRequest -ToolName $ToolName -Arguments $Arguments -SessionId $SessionId -UseFallback:$UseFallback -CorrelationId $CorrelationId}
function Get-MCPCrossPackEvidence{[CmdletBinding()]param([string]$Claim,[string[]]$SourcePacks=@(),[double]$MinConfidence=0.5,[string]$SessionId='',[string]$CorrelationId='') [pscustomobject]@{claim=$Claim;sourcePacks=$SourcePacks;evidence=@();minConfidence=$MinConfidence;correlationId=$CorrelationId}}
function New-MCPCrossPackContext{[CmdletBinding()]param([string[]]$PackIds,[hashtable]$InitialData=@{},[string]$SessionId='',[int]$ExpiryMinutes=30,[string]$CorrelationId='') if(-not $SessionId){$SessionId=(New-MCPSession -ContextData $InitialData -ExpiryMinutes $ExpiryMinutes).sessionId}; [pscustomobject]@{sessionId=$SessionId;packIds=$PackIds;data=$InitialData;correlationId=$CorrelationId}}
function Invoke-MCPBlenderToGodotExport{[CmdletBinding()]param([string]$SourcePath,[string]$OutputPath,[hashtable]$Options=@{},[string]$SessionId='',[switch]$WaitForCompletion,[string]$CorrelationId='') [pscustomobject]@{pipelineId=New-CorrelationId;sourcePath=$SourcePath;outputPath=$OutputPath;status='queued';options=$Options}}
function Get-MCPPipelineStatus{[CmdletBinding()]param([string]$PipelineId,[switch]$IncludeHistory) $script:GatewayState.pipelines[$PipelineId]}
function Register-MCPPipelineStep{[CmdletBinding()]param([string]$PipelineId,[hashtable]$StepConfig,[string[]]$DependsOn=@()) if(-not $script:GatewayState.pipelines[$PipelineId]){$script:GatewayState.pipelines[$PipelineId]=@{pipelineId=$PipelineId;steps=@()}}; $script:GatewayState.pipelines[$PipelineId].steps+=@{step=$StepConfig;dependsOn=$DependsOn}; $script:GatewayState.pipelines[$PipelineId]}
Export-ModuleMember -Function @('New-MCPCompositeGateway','Start-MCPCompositeGateway','Stop-MCPCompositeGateway','Start-MCPGateway','Stop-MCPGateway','Get-MCPCompositeGatewayStatus','Add-MCPPackRoute','Remove-MCPPackRoute','Register-MCPPackRoute','Unregister-MCPPackRoute','Get-MCPPackRoutes','Get-MCPPackRoute','Route-MCPRequest','Invoke-MCPGatewayRequest','Invoke-MCPPackRoute','Get-MCPGatewayManifest','Get-MCPAggregatedTools','Test-MCPGatewayHealth','Resolve-MCPToolTarget','Process-MCPGatewayRequest','Invoke-MCPCrossPackQuery','Invoke-MCPAggregatedTool','Get-MCPCrossPackEvidence','New-MCPCrossPackContext','Invoke-MCPBlenderToGodotExport','Get-MCPPipelineStatus','Register-MCPPipelineStep','New-MCPSession','Get-MCPSession','Remove-MCPSession','Update-SessionContext','Test-MCPCircuitBreaker','Record-MCPSuccess','Record-MCPFailure','Reset-MCPCircuitBreaker','Test-MCPRateLimit','Get-MCPRateLimitStatus')
